name: Build iOS IPA

on:
  workflow_dispatch: # Allows you to trigger the build manually

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Expo Prebuild
        run: npx expo prebuild --platform ios

      - name: Build unsigned IPA
        run: |
          cd ios
          # Compile the app without code signing
          xcodebuild -workspace *.xcworkspace -scheme $(ls -1 *.xcworkspace | sed 's/\.xcworkspace//') -configuration Release -sdk iphoneos CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" SYMROOT=$(PWD)/build build

          # Package the compiled .app into an .ipa file
          cd build/Release-iphoneos
          mkdir Payload
          mv *.app Payload/
          zip -r app.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: ios/build/Release-iphoneos/app.ipa