name: Build iOS IPA

on:
  workflow_dispatch: # Allows you to trigger the build manually

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Expo Prebuild
        run: npx expo prebuild --platform ios
      - name: Build unsigned IPA
        run: |
          cd ios
          # Find the workspace file
          WORKSPACE=$(ls -1 *.xcworkspace | head -n 1)
          
          # Automatically detect the correct scheme from the workspace
          SCHEME=$(xcodebuild -workspace "$WORKSPACE" -list | awk '/Schemes:/{getline; print $1}')
          
          # Build using the detected workspace and scheme
          xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release -sdk iphoneos CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" SYMROOT=$(PWD)/build build
          
          cd build/Release-iphoneos
          mkdir Payload
          mv *.app Payload/
          zip -r app.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: ios/build/Release-iphoneos/app.ipa
